[package]
name = "serenade-messenger"
description = "Sync message bus, middleware, and async transport adapters"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
