[package]
name = "serenade-config"
description = "Layered configuration loading and merging"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde_json = { workspace = true }
serde_yaml = { workspace = true }
serenade-di = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
